### ISSUE TITLE
compliance to specs

### ISSUE THREAD

**Issue by matthiasg** [MatAtBread/nodent#10]
great library so far.. i am a little concerned though about the comments from the babel community.. see https://github.com/babel/babel/issues/2515#issuecomment-147144405 .. which spec are you following in your tests ? (i know its not finalized of course)

**Comment by MatAtBread** [comment]
I've asked for some classification. TBH I have no idea what parts of the spec @sebmck thinks I've missed, but it's a learning exercise and if I've missed something I'll probably fix it. For us, nodent is in use in a production environment doing over 45m http operations per day, and the performance advantages of syntax transformation over generators is hugely significant

**Comment by matthiasg** [comment]
I would also think generators are not the way to go here, even if it is conceptually simpler.  Arrive a compiler has to be involved anyway rewriting the AST seems beneficial. It's also what e.g c# did when it came to supporting that...

My time for experimenting with sync ran out sadly.i will revisit this next weekend since I have a specific deadline this week and cannot invest more time before that.

Your implementation looks good though.I will do more tests as soon as I can.

----- Ursprüngliche Nachricht -----
Von: "Matt" <notifications@github.com>
Gesendet: ‎11.‎10.‎2015 22:24
An: "MatAtBread/nodent" <nodent@noreply.github.com>
Cc: "matthiasg" <mgt576@gmail.com>
Betreff: Re: [nodent] compliance to specs (#10)

I've asked for some classification. TBH I have no idea what parts of the spec @sebmck thinks I've missed, but it's a learning exercise and if I've missed something I'll probably fix it. For us, nodent is in use in a production environment doing over 45m http operations per day, and the performance advantages of syntax transformation over generators is hugely significant

**Comment by MatAtBread** [comment]
@sebmck - I've been through the tests in the Babel file you pointed me at. Other than the tests for the regenerator runtime, Promises and async generators (which nodent doesn't attempt to implement), the only failure cases are where the test is dependant on the state of the returned Promise between the invocation of the async function and the call to'then'. This does not form part of the specification and is principally due to the implementation of both the installed Promise library and generator implementation.

Nodent creates functions of the form
````
  function (...) {
    return new Promise (...) ;
  }
````
just as the specification calls for, and await resolves by calling 'then'. In generator mode, it generates code almost identical to the suggested algorithm in the spec, so I think your comments in this case are incorrect.

FWIW, I'd suggest avoiding using Babel or Traceur for implementing async and await in ES5 as the performance is very poor - between 5 and 10 slower that using a Promise- or callback- based implementation.

To borrow @mathiasg words, "generators are not the way to go here, even if it is conceptually simpler" as their performance and memory requirements are, with current engines, vastly inferior.

As you know from when you pointed out the lack of keyword contextualisation, I'm always interested in improving compliance and performance, but in this case I think you're mistaken and the tests reflect regenerator's execution order rather than the specification.

I notice we're both based in London, so I'd be happy to meet for a beer and compare solutions :) I might even learn something.
