### ISSUE TITLE
Chained awaits not transpiled correct

### ISSUE THREAD

**Issue by spielzeugland** [MatAtBread/nodent#110]
When transpiling the following code:
  await (await a()).b()
the first await is not converted.

See:
http://nodent.mailed.me.uk/#await%20(await%20a()).b()%0A~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22native%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Afalse%2C%22wrapAwait%22%3Atrue%2C%22spec%22%3Afalse%7D

Would be great to get some help from you.

**Comment by spielzeugland** [comment]
The problem occurs when trying to transpile usage of "await" outside of an async-function. Of course this would not be valid JavaScript, but was convenient for me as I am creating new functions from the output with "new Function(<output>)".
When surrounding the code above with an async-function it works as expected. Maybe you should throw an exception in this case. Babel also does not allow this as well.

**Comment by MatAtBread** [comment]
It's a good catch - I'll have a look and see what I can find

**Comment by MatAtBread** [comment]
Looking at this again, this is by design. The 'await outside an async function' ONLY works where await cannot be parsed into valid JS, and in `await (await x)` the first one looks like a call to a function called `await`.

Without this, nodent would break existing JS code that had an identifier called `await` that referenced a function.
