### ISSUE TITLE
can't make global.$error work

### ISSUE THREAD

**Issue by astoilkov** [MatAtBread/nodent#44]
Whatever I do I can't make `global.$error` to be called? Can this be a bug or I am missing something. Thanks.

Executing the code doesn't log anything. If I remove the `reject()` call the code logs "work done".
```js
'use nodent';


async function doWork() {
  var result = await getPromise();

  console.log(result);
}

function getPromise() {
  return new Promise(function (resolve, reject) {
    reject('error');

    setTimeout(function () {
      resolve('work done');
    });
  });
}

global.$error = function () {
  console.log('global error');
};

doWork();
```

**Comment by matAtWork** [comment]
Depending on exactly what compilation flags you are using (-es7, -promises, -generators), the reason is probably because you need to `await doWork()` at the end. Without the await, there is no way to handle the result of 'getPromise', and whatever Promise implementation you are using will have it's own way to handle unresolved Promises.

I Node v6.x, to handle unresolved rejections, the magic line is:

```
process.on('unhandledRejection', function(reason) {
    /// whatever
});
```

I'll close for now, but feel free to re-open if this doesn't help you out

**Comment by astoilkov** [comment]
Thanks a lot for the information. I have a more complicated example...this was an isolated case. I will try the `unhandledRejection` event there. Thanks again!
