### ISSUE TITLE
Let destructuring hoisting incompatible w/Buble

### ISSUE THREAD

**Issue by Akkuma** [MatAtBread/nodent#48]
If you write something like
```
async function test() {
    let { x } = await something()
}
```

the output is
```
function test() {
    return new Promise((function ($return, $error) {
        let x;
        return something().then((function ($await_1) {
            ({x} = $await_1);
            return $return();
        }).$asyncbind(this, $error), $error);
    }).$asyncbind(this));
}
```

Buble then fails to convert this to ES5 https://buble.surge.sh/#function%20test()%20%7B%0A%20%20%20%20return%20new%20Promise((function%20(%24return%2C%20%24error)%20%7B%0A%20%20%20%20%20%20%20%20let%20x%3B%0A%20%20%20%20%20%20%20%20return%20something().then((function%20(%24await_1)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20(%7Bx%7D%20%3D%20%24await_1)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%24return()%3B%0A%20%20%20%20%20%20%20%20%7D).%24asyncbind(this%2C%20%24error)%2C%20%24error)%3B%0A%20%20%20%20%7D).%24asyncbind(this))%3B%0A%7D%0A

**Comment by matAtWork** [comment]
I don't know "Buble", but the link you gave shows the error "Destructuring assignments are not currently supported. Coming soon! (5:13)" (see bottom left of the window). Either try another transpiler (Babel?), or don't use destructuring.

Nodent attempts to do as few transformations as possible to implement async & await, but if you use ES6 in the source (e.g. let and destructuring), it expects the runtime platform to support ES6, rather than just some selected parts of ES6.

This appears to be a Buble issue, not a Nodent issue, so I'll close unless you have some other related question.

**Comment by Akkuma** [comment]
Destructuring actually is supported, so it seems to be giving an improper error: https://buble.surge.sh/#let%20%7Bt%7D%20%3D%20something()

**Comment by matAtWork** [comment]
Buble seems to support destructuring _declaration_, but not destructuring _assigment_. Nodent has to separate declaration and assignment when you use `await` to maintain the scope of the variable, whilst only assigning it after the await has completed.

**Comment by MatAtBread** [comment]
EG:. https://buble.surge.sh/#let%20t%3B%0A(%7Bt%7D%20%3D%20something())
