### ISSUE TITLE
Do I have to use try/catch every time?

### ISSUE THREAD

**Issue by steebchen** [MatAtBread/nodent#49]
I am using [express](http://expressjs.com) and I am `await`ing [mongoose](http://mongoosejs.com/) queries, which works perfectly. However, when using await in an url route and an error occurrs, I (and [bugsnag](http://bugsnag.com)) can't catch the error in this specific route and thus the request times out - except when I always wrap this route with a try catch:

```
app.get('/:test*', async function(req, res, next) {
    let test = await Test.findOne({
        _id: req.params.test
    })

    nonExistingFunction() // error gets thrown, but I can only catch it globally with global.$error
    res.send(test)
})
```

```
app.get('/:test*', async function(req, res, next) {
    try {
        let test = await Test.findOne({
            _id: req.params.test
        })

        nonExistingFunction()
        res.send(test)
    } catch (e) {
        next(e) // error is successfully caught and an error message gets send to the user
    }
})
```

Is this expected behavior or is there a way to catch the errors without wrapping a try catch around the routes? I know I can use `global.$error` to catch the error, but the user still gets a timeout instead of an error message.

**Comment by matAtWork** [comment]
This is the expected behaviour - the callback for app.get() expects a 'function', and doesn't know about 'async function', so it just calls it (which causes it to run as normal). However, it has no way handle exceptions asynchronously. The nodent global.$error can be used to catch these "unhandled" errors, as can your Promise's library implementation (see https://github.com/MatAtBread/nodent/issues/44). In node v6 the native handler is:

```
process.on('unhandledRejection', function(reason) {
    /// whatever
});
```

In the example you are using, I simply wrap everything with something like:

```
function asyncRoute(fn) {
    return function(req,res,next) {
        try {
            await fn(req,res,next) ;
        } catch (ex) {
            res.status(500).send(ex.message) ;
        }
    }
}

async function theRoute(req,res,next) {
    ....
}

app.get('/', asyncRoute(theRoute)) ;

```

I'll close as this is not a bug, but feel free to ask for more info if necessary.

**Comment by steebchen** [comment]
Thank for the clarification, even if the same error occurs regardless of whether I use `async function` or `function` only in the second app.get parameter. Whatever, I'll use the asyncFunction which seems really minimal to "fix" my issue.
