### ISSUE TITLE
export * as name from './somewhere' unsupported

### ISSUE THREAD

**Issue by Akkuma** [MatAtBread/nodent#58]
While running through nodent-loader, I'm encountering an error when nodent sees the syntax `export * as name from './somewhere'`.

I've worked around it for now by using `import * as name from './somewhere'; export { name as name };`

**Comment by matAtWork** [comment]
Hmmm. Looks like in a bug in might be a bug in Acorn. The issue exists in both Acorn 3 and 4 (and can be verified at astexplorer.net), however quite a few parsers don't accept it (espree, esprima, recast, shift and Uglify all reject it).

Acorn is a very strict JS parser, and I'm not sure that syntax is actually in the spec. It's not mentioned in https://developer.mozilla.org/en/docs/web/javascript/reference/statements/export, and MDN is pretty definitive. A surprising number of common constructs are not actually in the ECMA spec.

If you feel it is a bug, can I ask you to report it as an issue at https://github.com/ternjs/acorn - mention me so I see the thread. Assuming it gets fixed I'll import the fix into nodent.

I'm going to close the issue here, not because it's not an issue for you, but because the fix needs to be in acorn, not nodent, if indeed it is valid JS.
