### ISSUE TITLE
Outer `finally` is called after nested async function

### ISSUE THREAD

**Issue by le0nik** [MatAtBread/nodent#89]
Here's a demo where I use `Promise.mapSeries` from `bluebird`. If you run this code you'll see that `test finally` is logged after each request in `mapSeries` and then is logged once again after all requests are completed. I think this might be a naming conflict. Please let me know if I can provide more info.

http://nodent.mailed.me.uk/#function%20makeRequest(id)%20%7B%0A%20%20%20%20return%20function%20request()%20%7B%0A%20%20%20%20%20%20%20%20return%20new%20Promise(resolve%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20resolve(%60success%20for%20%24%7Bid%7D%60)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%205)%3B%0A%20%20%20%20%20%20%20%20%7D)%3B%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%7D%0A%0Aasync%20function%20test()%20%7B%0A%20%20%20%20let%20responses%3B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20const%20requests%20%3D%20%5BmakeRequest('1')%2C%20makeRequest('2')%2C%20makeRequest('3')%5D%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20await%20Promise.mapSeries(requests%2C%20async%20req%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20response%20%3D%20await%20req()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('response'%2C%20response)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20response%3B%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%20finally%20%7B%0A%20%20%20%20%20%20%20%20console.log('test%20finally')%3B%0A%20%20%20%20%7D%0A%7D%0A%0Aawait%20test()%3B~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22bluebird%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Atrue%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

**Comment by matAtWork** [comment]
Yeah, that's a bug. The `return response` is incorrectly treated as a `return` that should be mapped to call `finally`. Clearly it's not as it's nested within a different async function.

**Comment by matAtWork** [comment]
Here's a (temporary) workaround:

http://nodent.mailed.me.uk/#function%20makeRequest(id)%20%7B%0A%20%20%20%20return%20function%20request()%20%7B%0A%20%20%20%20%20%20%20%20return%20new%20Promise(resolve%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20resolve(%60success%20for%20%24%7Bid%7D%60)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%205)%3B%0A%20%20%20%20%20%20%20%20%7D)%3B%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%7D%0A%0Aasync%20function%20test()%20%7B%0A%20%20%20%20let%20responses%3B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20const%20requests%20%3D%20%5BmakeRequest('1')%2C%20makeRequest('2')%2C%20makeRequest('3')%5D%3B%0A%20%20%20%20%20%20%20%20async%20function%20z(req)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20response%20%3D%20await%20req()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('response'%2C%20response)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20response%3B%0A%20%20%20%20%20%20%20%20%7D%20%3B%0A%20%20%20%20%20%20%20%20await%20Promise.mapSeries(requests%2C%20z)%3B%0A%20%20%20%20%7D%20finally%20%7B%0A%20%20%20%20%20%20%20%20console.log('test%20finally')%3B%0A%20%20%20%20%7D%0A%7D%0A%0Aawait%20test()%3B~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22bluebird%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Atrue%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

This works because by declaring  a function `z` instead of using an inline expression, the function (and its `return`) is hoisted outside the try-catch-finally block. A proper fix is on the way.

**Comment by matAtWork** [comment]
Fix shipped in v3.0.19. Thanks for the report!
